// Generated by CoffeeScript 1.6.2
(function() {
  var Router, commands, mediocre, type;

  mediocre = require("mediocre");

  commands = require("./commands");

  type = require("type-component");

  Router = (function() {
    /*
    */
    function Router() {
      this._mediator = mediocre();
      this._mediator.router = this;
      this.on(commands);
    }

    /*
    */


    Router.prototype.on = function(nameOrRoutes, listener) {
      var name;

      if (type(nameOrRoutes) === "object") {
        for (name in nameOrRoutes) {
          this.on(name, nameOrRoutes[name]);
        }
        return;
      }
      this._mediator.on(nameOrRoutes, listener);
      return this;
    };

    /*
    */


    Router.prototype.redirect = function() {};

    return Router;

  })();

  module.exports = function(routes) {
    var router;

    if (routes == null) {
      routes = {};
    }
    router = new Router();
    router.on(routes);
    return function(mojo) {
      router.models = mojo.models;
      return mojo.router = router;
    };
  };

}).call(this);
